merk_notification_user_preferences_new:
    pattern: /new
    defaults:
        _controller: merkNotificationBundle:UserPreferences:new

merk_notification_user_preferences_edit:
    pattern: /edit
    defaults:
        _controller: merkNotificationBundle:UserPreferences:edit